import React, { useState, useEffect } from 'react';
import {
  StyleSheet, Text, View, TextInput,
    TouchableOpacity, FlatList, SafeAreaView
    } from 'react-native';
    import {
      collection, addDoc, onSnapshot,
        updateDoc, deleteDoc, doc
        } from 'firebase/firestore';
        import { db } from '../../firebaseConfig';

        type GroceryItem = {
          id: string;
            name: string;
              checked: boolean;
              };

              export default function App() {
                const [items, setItems] = useState<GroceryItem[]>([]);
                  const [text, setText] = useState<string>('');

                    useEffect(() => {
                        const unsub = onSnapshot(collection(db, 'groceries'), snapshot => {
                              setItems(snapshot.docs.map(d => ({
                                      id: d.id,
                                              name: d.data().name,
                                                      checked: d.data().checked
                                                            })));
                                                                });
                                                                    return unsub;
                                                                      }, []);

                                                                        const addItem = async () => {
                                                                            if (text.trim() === '') return;
                                                                                await addDoc(collection(db, 'groceries'), {
                                                                                      name: text.trim(),
                                                                                            checked: false
                                                                                                });
                                                                                                    setText('');
                                                                                                      };

                                                                                                        const toggleItem = async (item: GroceryItem) => {
                                                                                                            await updateDoc(doc(db, 'groceries', item.id), {
                                                                                                                  checked: !item.checked
                                                                                                                      });
                                                                                                                        };

                                                                                                                          const deleteItem = async (id: string) => {
                                                                                                                              await deleteDoc(doc(db, 'groceries', id));
                                                                                                                                };

                                                                                                                                  return (
                                                                                                                                      <SafeAreaView style={styles.container}>
                                                                                                                                            <Text style={styles.title}>🛒 Grocery List</Text>
                                                                                                                                                  <View style={styles.inputRow}>
                                                                                                                                                          <TextInput
                                                                                                                                                                    style={styles.input}
                                                                                                                                                                              placeholder="Add an item..."
                                                                                                                                                                                        value={text}
                                                                                                                                                                                                  onChangeText={setText}
                                                                                                                                                                                                          />
                                                                                                                                                                                                                  <TouchableOpacity style={styles.addBtn} onPress={addItem}>
                                                                                                                                                                                                                            <Text style={styles.addBtnText}>Add</Text>
                                                                                                                                                                                                                                    </TouchableOpacity>
                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                <FlatList
                                                                                                                                                                                                                                                        data={items}
                                                                                                                                                                                                                                                                keyExtractor={(i: GroceryItem) => i.id}
                                                                                                                                                                                                                                                                        renderItem={({ item }: { item: GroceryItem }) => (
                                                                                                                                                                                                                                                                                  <View style={styles.itemRow}>
                                                                                                                                                                                                                                                                                              <TouchableOpacity onPress={() => toggleItem(item)} style={styles.itemLeft}>
                                                                                                                                                                                                                                                                                                            <Text style={styles.checkbox}>{item.checked ? '✅' : '⬜'}</Text>
                                                                                                                                                                                                                                                                                                                          <Text style={[styles.itemText, item.checked && styles.checked]}>
                                                                                                                                                                                                                                                                                                                                          {item.name}
                                                                                                                                                                                                                                                                                                                                                        </Text>
                                                                                                                                                                                                                                                                                                                                                                    </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                <TouchableOpacity onPress={() => deleteItem(item.id)}>
                                                                                                                                                                                                                                                                                                                                                                                              <Text style={styles.delete}>🗑️</Text>
                                                                                                                                                                                                                                                                                                                                                                                                          </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                    </View>
                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                      </SafeAreaView>
                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                        const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                          container: { flex: 1, backgroundColor: '#fff', paddingHorizontal: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                            title: { fontSize: 28, fontWeight: 'bold', marginVertical: 20, textAlign: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                              inputRow: { flexDirection: 'row', marginBottom: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                input: { flex: 1, borderWidth: 1, borderColor: '#ccc', borderRadius: 8, padding: 10, fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                  addBtn: { backgroundColor: '#4CAF50', padding: 10, borderRadius: 8, marginLeft: 10, justifyContent: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                    addBtnText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                      itemRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#eee' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                        itemLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                          checkbox: { fontSize: 20, marginRight: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                            itemText: { fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                              checked: { textDecorationLine: 'line-through', color: '#aaa' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                delete: { fontSize: 20 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                });