import React, { useState, useEffect } from 'react';
import {
  StyleSheet, Text, View, TextInput,
    TouchableOpacity, FlatList, SafeAreaView
    } from 'react-native';
    import {
      collection, addDoc, onSnapshot,
        updateDoc, deleteDoc, doc
        } from 'firebase/firestore';
        import {
          getAuth, signInWithPopup, GoogleAuthProvider,
            signOut, onAuthStateChanged, User
            } from 'firebase/auth';
            import { db } from '../../firebaseConfig';

            const auth = getAuth();
            const provider = new GoogleAuthProvider();

            type GroceryItem = {
              id: string;
                name: string;
                  checked: boolean;
                    addedBy: string;
                    };

                    export default function App() {
                      const [items, setItems] = useState<GroceryItem[]>([]);
                        const [text, setText] = useState<string>('');
                          const [user, setUser] = useState<User | null>(null);

                            useEffect(() => {
                                const unsub = onAuthStateChanged(auth, (u) => setUser(u));
                                    return unsub;
                                      }, []);

                                        useEffect(() => {
                                            if (!user) return;
                                                const unsub = onSnapshot(collection(db, 'groceries'), snapshot => {
                                                      setItems(snapshot.docs.map(d => ({
                                                              id: d.id,
                                                                      name: d.data().name,
                                                                              checked: d.data().checked,
                                                                                      addedBy: d.data().addedBy
                                                                                            })));
                                                                                                });
                                                                                                    return unsub;
                                                                                                      }, [user]);

                                                                                                        const signIn = async () => {
                                                                                                            await signInWithPopup(auth, provider);
                                                                                                              };

                                                                                                                const signOutUser = async () => {
                                                                                                                    await signOut(auth);
                                                                                                                      };

                                                                                                                        const addItem = async () => {
                                                                                                                            if (text.trim() === '' || !user) return;
                                                                                                                                await addDoc(collection(db, 'groceries'), {
                                                                                                                                      name: text.trim(),
                                                                                                                                            checked: false,
                                                                                                                                                  addedBy: user.displayName || user.email
                                                                                                                                                      });
                                                                                                                                                          setText('');
                                                                                                                                                            };

                                                                                                                                                              const toggleItem = async (item: GroceryItem) => {
                                                                                                                                                                  await updateDoc(doc(db, 'groceries', item.id), {
                                                                                                                                                                        checked: !item.checked
                                                                                                                                                                            });
                                                                                                                                                                              };

                                                                                                                                                                                const deleteItem = async (id: string) => {
                                                                                                                                                                                    await deleteDoc(doc(db, 'groceries', id));
                                                                                                                                                                                      };

                                                                                                                                                                                        if (!user) {
                                                                                                                                                                                            return (
                                                                                                                                                                                                  <SafeAreaView style={styles.loginContainer}>
                                                                                                                                                                                                          <Text style={styles.title}>🛒 Grocery List</Text>
                                                                                                                                                                                                                  <Text style={styles.subtitle}>Sign in to access the shared list</Text>
                                                                                                                                                                                                                          <TouchableOpacity style={styles.googleBtn} onPress={signIn}>
                                                                                                                                                                                                                                    <Text style={styles.googleBtnText}>🔑 Sign in with Google</Text>
                                                                                                                                                                                                                                            </TouchableOpacity>
                                                                                                                                                                                                                                                  </SafeAreaView>
                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                              <SafeAreaView style={styles.container}>
                                                                                                                                                                                                                                                                    <View style={styles.header}>
                                                                                                                                                                                                                                                                            <Text style={styles.title}>🛒 Grocery List</Text>
                                                                                                                                                                                                                                                                                    <TouchableOpacity onPress={signOutUser}>
                                                                                                                                                                                                                                                                                              <Text style={styles.signOut}>Sign out</Text>
                                                                                                                                                                                                                                                                                                      </TouchableOpacity>
                                                                                                                                                                                                                                                                                                            </View>
                                                                                                                                                                                                                                                                                                                  <Text style={styles.welcome}>👋 {user.displayName}</Text>
                                                                                                                                                                                                                                                                                                                        <View style={styles.inputRow}>
                                                                                                                                                                                                                                                                                                                                <TextInput
                                                                                                                                                                                                                                                                                                                                          style={styles.input}
                                                                                                                                                                                                                                                                                                                                                    placeholder="Add an item..."
                                                                                                                                                                                                                                                                                                                                                              value={text}
                                                                                                                                                                                                                                                                                                                                                                        onChangeText={setText}
                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                        <TouchableOpacity style={styles.addBtn} onPress={addItem}>
                                                                                                                                                                                                                                                                                                                                                                                                  <Text style={styles.addBtnText}>Add</Text>
                                                                                                                                                                                                                                                                                                                                                                                                          </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                </View>
                                                                                                                                                                                                                                                                                                                                                                                                                      <FlatList
                                                                                                                                                                                                                                                                                                                                                                                                                              data={items}
                                                                                                                                                                                                                                                                                                                                                                                                                                      keyExtractor={(i: GroceryItem) => i.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                              renderItem={({ item }: { item: GroceryItem }) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <View style={styles.itemRow}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <TouchableOpacity onPress={() => toggleItem(item)} style={styles.itemLeft}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Text style={styles.checkbox}>{item.checked ? '✅' : '⬜'}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Text style={[styles.itemText, item.checked && styles.checked]}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {item.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Text style={styles.addedBy}>Added by {item.addedBy}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <TouchableOpacity onPress={() => deleteItem(item.id)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Text style={styles.delete}>🗑️</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </SafeAreaView>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  loginContainer: { flex: 1, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', padding: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    container: { flex: 1, backgroundColor: '#fff', paddingHorizontal: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginVertical: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title: { fontSize: 28, fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          subtitle: { fontSize: 16, color: '#666', marginBottom: 30 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            welcome: { fontSize: 16, color: '#666', marginBottom: 15 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              signOut: { fontSize: 14, color: '#f44336' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                googleBtn: { backgroundColor: '#4285F4', padding: 15, borderRadius: 10, width: '100%', alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  googleBtnText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    inputRow: { flexDirection: 'row', marginBottom: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      input: { flex: 1, borderWidth: 1, borderColor: '#ccc', borderRadius: 8, padding: 10, fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        addBtn: { backgroundColor: '#4CAF50', padding: 10, borderRadius: 8, marginLeft: 10, justifyContent: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          addBtnText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            itemRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#eee' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              itemLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                checkbox: { fontSize: 20, marginRight: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  itemText: { fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    addedBy: { fontSize: 12, color: '#999' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      checked: { textDecorationLine: 'line-through', color: '#aaa' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        delete: { fontSize: 20 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });